/** Bravo Charlie SEO Hub extension schema for OpenSEO PostgreSQL. */
import { sql } from "drizzle-orm";
import { boolean, index, integer, pgTable, serial, text, uniqueIndex } from "drizzle-orm/pg-core";
import { organization, user } from "./better-auth-schema";
import { projects } from "./app.schema";

const isoNow = sql`to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')`;
const timestampColumn = (name: string) => text(name);

export const bcClients = pgTable("bc_clients", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }), name: text("name").notNull(), slug: text("slug").notNull(), status: text("status", { enum: ["onboarding", "active", "paused", "archived"] }).notNull().default("onboarding"), publicProofEnabled: boolean("public_proof_enabled").notNull().default(false), createdAt: timestampColumn("created_at").notNull().default(isoNow), updatedAt: timestampColumn("updated_at").notNull().default(isoNow) }, (table) => [uniqueIndex("bc_clients_org_slug_idx").on(table.organizationId, table.slug), index("bc_clients_org_status_idx").on(table.organizationId, table.status)]);

export const bcClientProjects = pgTable("bc_client_projects", { clientId: text("client_id").notNull().references(() => bcClients.id, { onDelete: "cascade" }), projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), label: text("label"), isPrimary: boolean("is_primary").notNull().default(false), createdAt: timestampColumn("created_at").notNull().default(isoNow) }, (table) => [uniqueIndex("bc_client_projects_project_idx").on(table.projectId), uniqueIndex("bc_client_projects_client_project_idx").on(table.clientId, table.projectId), index("bc_client_projects_client_idx").on(table.clientId)]);

export const bcClientUserAccess = pgTable("bc_client_user_access", { clientId: text("client_id").notNull().references(() => bcClients.id, { onDelete: "cascade" }), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), role: text("role", { enum: ["viewer", "approver"] }).notNull().default("viewer"), createdAt: timestampColumn("created_at").notNull().default(isoNow) }, (table) => [uniqueIndex("bc_client_user_access_unique_idx").on(table.clientId, table.userId), index("bc_client_user_access_user_idx").on(table.userId)]);

export const bcWpRegistrationCodes = pgTable("bc_wp_registration_codes", { id: text("id").primaryKey(), projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), codeHash: text("code_hash").notNull(), expiresAt: timestampColumn("expires_at").notNull(), consumedAt: timestampColumn("consumed_at"), createdByUserId: text("created_by_user_id").notNull().references(() => user.id, { onDelete: "cascade" }), createdAt: timestampColumn("created_at").notNull().default(isoNow) }, (table) => [uniqueIndex("bc_wp_registration_codes_hash_idx").on(table.codeHash), index("bc_wp_registration_codes_project_idx").on(table.projectId, table.expiresAt)]);

export const bcWpSites = pgTable("bc_wp_sites", { id: text("id").primaryKey(), siteId: text("site_id").notNull(), projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), siteUrl: text("site_url").notNull(), siteName: text("site_name").notNull(), secretCiphertext: text("secret_ciphertext").notNull(), secretFingerprint: text("secret_fingerprint").notNull(), statusEndpoint: text("status_endpoint").notNull(), updateEndpoint: text("update_endpoint").notNull(), pluginVersion: text("plugin_version").notNull(), wordpressVersion: text("wordpress_version"), capabilitiesJson: text("capabilities_json").notNull().default("[]"), lastHeartbeatAt: timestampColumn("last_heartbeat_at"), lastHealthScore: integer("last_health_score"), last404Hits: integer("last_404_hits").notNull().default(0), lastCwvAssessment: text("last_cwv_assessment"), registeredAt: timestampColumn("registered_at").notNull().default(isoNow), updatedAt: timestampColumn("updated_at").notNull().default(isoNow) }, (table) => [uniqueIndex("bc_wp_sites_site_id_idx").on(table.siteId), uniqueIndex("bc_wp_sites_project_idx").on(table.projectId), uniqueIndex("bc_wp_sites_url_idx").on(table.siteUrl), index("bc_wp_sites_heartbeat_idx").on(table.lastHeartbeatAt)]);

export const bcWpSiteSnapshots = pgTable("bc_wp_site_snapshots", { id: serial("id").primaryKey(), wpSiteId: text("wp_site_id").notNull().references(() => bcWpSites.id, { onDelete: "cascade" }), healthScore: integer("health_score"), missingDescriptions: integer("missing_descriptions"), missingTitles: integer("missing_titles"), noindexCount: integer("noindex_count"), error404Hits: integer("error_404_hits"), cwvJson: text("cwv_json"), auditSummaryJson: text("audit_summary_json"), capturedAt: timestampColumn("captured_at").notNull().default(isoNow) }, (table) => [index("bc_wp_site_snapshots_site_time_idx").on(table.wpSiteId, table.capturedAt)]);

export const bcApprovalQueue = pgTable("bc_approval_queue", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }), projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), wpSiteId: text("wp_site_id").references(() => bcWpSites.id, { onDelete: "set null" }), actionType: text("action_type", { enum: ["seo_meta", "redirect", "schema", "sitemap", "content", "other"] }).notNull(), title: text("title").notNull(), rationale: text("rationale"), evidenceJson: text("evidence_json").notNull().default("{}"), payloadJson: text("payload_json").notNull().default("{}"), status: text("status", { enum: ["pending", "approved", "rejected", "applied", "failed"] }).notNull().default("pending"), createdBy: text("created_by").notNull().default("seo-agent"), decidedByUserId: text("decided_by_user_id").references(() => user.id, { onDelete: "set null" }), createdAt: timestampColumn("created_at").notNull().default(isoNow), decidedAt: timestampColumn("decided_at"), appliedAt: timestampColumn("applied_at"), errorMessage: text("error_message") }, (table) => [index("bc_approval_queue_org_status_idx").on(table.organizationId, table.status, table.createdAt), index("bc_approval_queue_project_idx").on(table.projectId, table.createdAt)]);

export const bcPublicShowcase = pgTable("bc_public_showcase", { id: text("id").primaryKey(), clientId: text("client_id").notNull().references(() => bcClients.id, { onDelete: "cascade" }), projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), trackingKeywordId: text("tracking_keyword_id").notNull(), headline: text("headline"), enabled: boolean("enabled").notNull().default(false), approvedByUserId: text("approved_by_user_id").references(() => user.id, { onDelete: "set null" }), approvedAt: timestampColumn("approved_at"), createdAt: timestampColumn("created_at").notNull().default(isoNow) }, (table) => [uniqueIndex("bc_public_showcase_keyword_idx").on(table.projectId, table.trackingKeywordId), index("bc_public_showcase_enabled_idx").on(table.enabled, table.createdAt)]);
